version: "3"
services:
  # react-frontend:
  #   image: node:14-alpine
  #   ports:
  #     - "3000:3000"
  #   # networks:
  #   #   - react-flask-mongo
  #   volumes:
  #     - ./react-app:/app:cached
  #   working_dir: /app
  #   command: npm start
  #   tty: true
#   flask-backend:
#     image: flask-api
#     ports:
#       - "5000:5000"
#     networks:
#       - react-flask-mongo
#     depends_on:
#       - mongo-db
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_username
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
# networks:
#   react-flask-mongo:
#     driver: bridge
# volumes:
#   mongo-data:
#     driver: local